baseURL         = "https://mellium.im/"
enableRobotsTXT = false
languageCode    = "en-us"
theme           = ["modules"]
title           = "Mellium"
disableKinds = ["taxonomy", "taxonomyTerm"]

[author]

name  = "Sam Whited"
email = "sam@mellium.im"

[params]

logo = "mellium.svg"

[privacy]

	[privacy.disqus]
	disable = true

	[privacy.googleAnalytics]
	disable = true

	[privacy.instagram]
	disable = true

	[privacy.twitter]
	disable = true

	[privacy.vimeo]
	disable = true

	[privacy.youtube]
	disable = true
