image: alpine/edge
packages:
  - hugo
  - rsync
  - zip
secrets:
  - c02a5953-f276-413e-9c9a-c50ee3d84d52
  - fd26d009-95b8-4558-9ff4-1129c8b3c69c
sources:
  - https://github.com/mellium/mellium.im
triggers:
  - action: email
    condition: failure
    to: "sam@mellium.im"
tasks:
  - build: |
      cd mellium.im/
      hugo version
      hugo
  - deploy: |
      cd mellium.im/public
      rsync -e "ssh -p 222" -av --delete . deploy@mellium.im:/usr/local/www/mellium.im
